In [ ]:
#1  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
random_array = np.random.randint(1, 101, (3, 3))

# Interchange rows and columns (transpose)
interchanged_array = random_array.T

print("Original array:")
print(random_array)

print("Interchanged array:")
print(interchanged_array)

In [ ]:
#2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements
array = np.arange(10)  # Creates an array with elements [0, 1, 2, ..., 9]

# Print the original 1D array
print("Original 1D array:")
print(array)

# Step 2: Reshape the 1D array into a 2x5 array
reshaped_2x5 = array.reshape(2, 5)

# Print the 2x5 array
print("\nReshaped into 2x5 array:")
print(reshaped_2x5)

# Step 3: Reshape the 1D array into a 5x2 array
reshaped_5x2 = array.reshape(5, 2)

# Print the 5x2 array
print("\nReshaped into 5x2 array:")
print(reshaped_5x2)
Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Step 1: Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)  # Random float values between 0 and 1

# Print the original 4x4 array
print("Original 4x4 array:")
print(array_4x4)

# Step 2: Add a border of zeros around the 4x4 array to make it 6x6
# Use np.pad with 'constant' mode to add zeros
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the 6x6 array
print("\n6x6 array with border of zeros:")
print(array_6x6)
Original 4x4 array:
[[0.72875957 0.6945791  0.6428752  0.2564061 ]
 [0.67235878 0.74957064 0.66606053 0.26332377]
 [0.70252627 0.64245283 0.52448232 0.65745352]
 [0.33768991 0.45153934 0.15864546 0.65243874]]

6x6 array with border of zeros:
[[0. 0. 0. 0. 0. 0.]
 [0. 0.72875957 0.6945791  0.6428752  0.2564061  0.]
 [0. 0.67235878 0.74957064 0.66606053 0.26332377 0.]
 [0. 0.70252627 0.64245283 0.52448232 0.65745352 0.]
 [0. 0.33768991 0.45153934 0.15864546 0.65243874 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#4  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)  # The end value (65) is exclusive, so it goes up to 60

# Print the array
print(array)
[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
#5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Step 1: Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Print the original array
print("Original array:")
print(array)

# Apply different case transformations
uppercase_array = np.char.upper(array)  # Convert to uppercase
lowercase_array = np.char.lower(array)  # Convert to lowercase
titlecase_array = np.char.title(array)   # Convert to title case
capitalize_array = np.char.capitalize(array)  # Convert to capitalized (first letter uppercase, rest lowercase)

# Print the transformed arrays
print("\nUppercase array:")
print(uppercase_array)

print("\nLowercase array:")
print(lowercase_array)

print("\nTitlecase array:")
print(titlecase_array)

print("\nCapitalized array:")
print(capitalize_array)
Original array:
['python' 'numpy' 'pandas']

Uppercase array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase array:
['python' 'numpy' 'pandas']

Titlecase array:
['Python' 'Numpy' 'Pandas']

Capitalized array:
['Python' 'Numpy' 'Pandas']


In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Step 1: Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Print the original array
print("Original array:")
print(words_array)

# Step 2: Insert a space between each character of every word
# Use np.char.join to insert a space between each character
words_with_spaces = np.char.join(' ', words_array)

# Print the transformed array
print("\nArray with spaces between characters:")
print(words_with_spaces)
Original array:
['python' 'numpy' 'pandas']

Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Step 1: Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Print the original arrays
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Step 2: Perform element-wise addition
addition_result = array1 + array2
print("\nElement-wise addition:")
print(addition_result)

# Perform element-wise subtraction
subtraction_result = array1 - array2
print("\nElement-wise subtraction:")
print(subtraction_result)

# Perform element-wise multiplication
multiplication_result = array1 * array2
print("\nElement-wise multiplication:")
print(multiplication_result)

# Perform element-wise division
# Note: Make sure array2 does not contain zeros to avoid division by zero errors
division_result = array1 / array2
print("\nElement-wise division:")
print(division_result)
Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the identity matrix
print("5x5 Identity Matrix:")
print(identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the diagonal elements
print("\nDiagonal elements:")
print(diagonal_elements)
5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements:
[1. 1. 1. 1. 1.]


In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
array = np.random.randint(0, 1000, size=100)

# Print the generated array
print("Generated array:")
print(array)

# Step 2: Define a function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Step 3: Find and display all prime numbers in the array
prime_numbers = [num for num in array if is_prime(num)]

# Print the prime numbers
print("\nPrime numbers in the array:")
print(prime_numbers)
